# Generated by Django 5.2.7 on 2026-02-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0006_add_exam_session_and_assignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="instructions_open_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Allow viewing instructions this many minutes before start.",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="late_entry_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Allow starting the exam this many minutes after start.",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="grace_minutes",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Allow late submission this many minutes after exam end.",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="schedule_state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PROPOSED", "Proposed"),
                    ("APPROVED", "Approved"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="schedule_proposed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="schedule_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="schedule_proposed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_schedules_proposed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="schedule_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessment_schedules_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

