# Generated by Django 5.2.11 on 2026-02-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0006_update_snapshot_interval_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='is_encrypted',
            field=models.BooleanField(default=True, help_text='Indicates recording is stored with server-side encryption at rest'),
        ),
        migrations.AlterField(
            model_name='proctoringviolation',
            name='violation_type',
            field=models.CharField(choices=[('NO_FACE', 'No face detected'), ('MULTIPLE_FACES', 'Multiple faces detected'), ('LOOKING_AWAY', 'Looking away from screen'), ('FACE_NOT_MATCHED', 'Face does not match registered student'), ('AUDIO_TALKING', 'Background talking detected'), ('CAMERA_OFF', 'Camera turned off or unavailable'), ('OBJECT_DETECTED', 'Suspicious object detected'), ('PHONE_DETECTED', 'Phone detected in frame'), ('BOOK_DETECTED', 'Book or notes detected in frame'), ('LAPTOP_DETECTED', 'Secondary device detected'), ('PERSON_LEFT', 'Person left the frame'), ('INTERMITTENT_FACE', 'Face frequently disappearing'), ('PERSISTENT_GAZE_AWAY', 'Consistently looking away'), ('MULTIPLE_PERSONS_PATTERN', 'Multiple people detected over time'), ('IDENTITY_MISMATCH_PATTERN', 'Repeated face verification failures')], max_length=30),
        ),
    ]
