# Generated by Django 5.2.11 on 2026-02-15 12:49

import apps.proctoring.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_add_schedule_workflow_and_rules'),
        ('proctoring', '0007_sessionrecording_is_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringVideoClip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(blank=True, null=True, upload_to=apps.proctoring.models.proctoring_clip_upload_to)),
                ('video_url', models.URLField(blank=True, default='')),
                ('trigger_reason', models.CharField(choices=[('MULTIPLE_FACES', 'Multiple faces detected'), ('NO_FACE', 'No face detected'), ('LOOKING_AWAY', 'Looking away'), ('PHONE_DETECTED', 'Phone detected'), ('BOOK_DETECTED', 'Book/notes detected'), ('AUDIO_TALKING', 'Background talking detected'), ('TAB_SWITCH', 'Tab switch'), ('FULLSCREEN_EXIT', 'Fullscreen exited'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('trigger_description', models.TextField(blank=True, default='')),
                ('duration_seconds', models.PositiveIntegerField(default=30)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('severity', models.PositiveIntegerField(default=1, help_text='Severity level 1-5')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_clips', to='assessments.examsession')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['session', '-created_at'], name='proctoring__session_f0a282_idx'), models.Index(fields=['trigger_reason', '-created_at'], name='proctoring__trigger_614b87_idx')],
            },
        ),
    ]
